dependencies:
  # this is the same commit (4fa5311) as master branch of the upstream repo
  # hamdiallam/Solidity-RLP, but we have to use the fork since 2.0.4 tag is
  # not yet published in the upstream
  - skozin/Solidity-RLP@2.0.4

compiler:
  solc:
    version: 0.6.12
    optimizer:
      enabled: true
      runs: 200

networks:
  default: development
  development:
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: https://archive-node.address
